---
abstract: 'Async model layer for MongoDB objects using Mango'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.90
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mandel
no_index:
  directory:
    - t
    - inc
requires:
  Mango: 0.14
  Mojolicious: 3.40
  Type::Tiny: 0.014
resources:
  bugtracker: https://github.com/jhthorsen/mandel/issues
  homepage: https://metacpan.org/release/Mandel
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jhthorsen/mandel
version: 0.14
